name: weather

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Tree
      run: tree

    - name: npm install
      run: |
        node -v
        npm -version
        cd ${{ github.workspace }}/weather-app-main
        npm install
        cd ..
        tree
        

          
