name: weather

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Tree
      run: tree
      
    - name: Replace token
      run: |
        sed -i "s/#{OTHER_KEY}#/${{ secrets.API_KEY }}/g" ${{ github.workspace }}/weather-app-main/env.js
  
    - name: npm install
      run: |
        cd ${{ github.workspace }}/weather-app-main
        cat env.js
        
    - name: npm install
      run: |
        node -v
        npm -version
        cd ${{ github.workspace }}/weather-app-main
        npm install
        
    - name: npm run build
      run: |
        cd ${{ github.workspace }}/weather-app-main
        npm run build
        cd ..
        tree
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: 'Drop'
        path: '${{ github.workspace }}/weather-app-main/dist'

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: Drop
        path: ${{ github.workspace }}/build
        
    - name: npm run build
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_KEY }}
        cd ${{ github.workspace }}/weather-app-main
        docker build -t weather/nginx-front:latest .
        docker ps
        docker push weather/nginx-front:latest


          
