name: weather

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Tree
      run: tree
      
    - name: Replace token
      run: |
        sed -i "s/#{OTHER_KEY}#/${{ secrets.API_KEY }}/g" ${{ github.workspace }}/weather-app-main/env.js
  
    - name: secret check
      run: |
        cd ${{ github.workspace }}/weather-app-main
        cat env.js
        
    - name: npm install
      run: |
        node -v
        npm -version
        cd ${{ github.workspace }}/weather-app-main
        npm install
        
    - name: npm run build
      run: |
        cd ${{ github.workspace }}/weather-app-main
        npm run build
        cd ..
        tree
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: 'Drop'
        path: '${{ github.workspace }}/weather-app-main/dist'

  docker:
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: Drop
        path: ${{ github.workspace }}/dist
        
    - name: Move drop
      run: |
        tree
        mv ${{ github.workspace }}/dist ${{ github.workspace }}/weather-app-main

    - name: Docker build and push
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_KEY
        cd ${{ github.workspace }}/weather-app-main
        docker build -t $DOCKERHUB_USER/weather-nginx-front:${{ github.run_number }} .
        docker ps
        docker push $DOCKERHUB_USER/weather-nginx-front:${{ github.run_number }}


          
