name: weather

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Tree
      run: tree

    - name: npm install
      run: |
        node -v
        npm -version
        cd ${{ github.workspace }}/weather-app-main
        npm install
        
    - name: npm run build
      run: |
        cd ${{ github.workspace }}/weather-app-main
        npm run build
        cd ..
        tree
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: 'Drop'
        path: '${{ github.workspace }}/weather-app-main/dist'
          
